;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        ido-dired
        org-end-of-line
        sclang-clear-post-buffer
        sclang-main-stop
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-move
        ace-mc-add-char
        ace-mc-add-multiple-cursors
        ace-mc-add-single-cursor
        ace-mc-do-keyboard-reset
        comment-dwim
        end-of-buffer
        sclang-eval-region-or-line
        ))
